{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.serviceAccountName" . }}
  labels:
{{ include "controller.labels" . | nindent 4 }}
{{- end -}}
